Flag empty list concatenation
nerdypepper/statix pull request #50
Opened 2022-07-04 07:43 UTC by viraptor

`[] ++ something` should be reduced to just `something`

2022-07-10 13:42 UTC, nerdypepper requested changes
Thanks for the PR! Apart from minor code changes, there is one more addition: unit tests, please add snapshot data to `bin/tests/data` and run `cargo insta review`

2022-07-10 13:42 UTC, nerdypepper commented on lib/src/lints/empty_list_concat.rs
> +/// Checks for empty list being concatenated.
```suggestion
/// Checks for concatenations to empty lists
```

2022-07-10 13:42 UTC, nerdypepper commented on lib/src/lints/empty_list_concat.rs
> +    }
can we omit the use of the `if_chain` macro here?

2022-07-16 02:19 UTC, viraptor commented
Done, tests included.

2022-09-24 04:20 UTC, ilkecan approved these changes

2023-01-08 12:37 UTC, merged